/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HTrees;

import java.awt.Graphics;

/**
 *
 * @author john
 */
public class HtreesPanel extends javax.swing.JPanel {

    
    public HtreesPanel() {
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g); 
        int n = 4;//recursion time
        int x = 300, y = 300;// starting point of the tree
        int length = 300;// side length of the tree
        drawHTree(g, n, x, y, length);
    }
    
    public static void drawHTree(Graphics g, int n, int x, int y, int length) {
        if (n > 0){
            //calculate the four ends of the tree
            //which are the starting points of new trees
            int x1 = x - length/2;
            int y1 = y - length/2;
            int x2 = x + length/2;
            int y2 = y + length/2;      
            //draw H
            g.drawLine(x1, y1, x1, y2);//left "|"
            g.drawLine(x2, y1, x2, y2);//right "|"
            g.drawLine(x1,  y, x2,  y);//middle "—"
            //draw 4 new H-trees whose side length is half of the original tree
            drawHTree(g, n-1, x1, y1, length/2);
            drawHTree(g, n-1, x1, y2, length/2);
            drawHTree(g, n-1, x2, y1, length/2); 
            drawHTree(g, n-1, x2, y2, length/2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
