/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sierpinski;

import java.awt.*;

/**
 *
 * @author john
 */
public class SierpinskiPanel extends javax.swing.JPanel {

    public SierpinskiPanel() {
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g); 
        int n = 4;//recursion time
        int x = 400, y = 400;// mid-bottom point of the triangle
        int size = 200;// side length of the triangle
        drawSierpinski(g, n, x, y, size);
    }
    
    public static void drawSierpinski(Graphics g, int n, int x, int y, int size){
        int height = (int)(size * Math.sqrt(3));
        //draw the skeleton of the big triangle
        g.drawLine(x-size, y, x+size, y);
        g.drawLine(x-size, y, x, y - height);
        g.drawLine(x, y - height, x+size, y);
        //fill the middle small triangle
        triangle(g, x, y, size);
        if (n > 1) {
            //small triangle on the top
            triangle(g, x, y-height/2, size/2);
            drawSierpinski(g, n-1, x, y-height/2, size/2); 
            //small triangle at the left bottom corner
            triangle(g, x-size/2, y, size/2);
            drawSierpinski(g, n-1, x-size/2, y, size/2); 
            //small triangle at the right bottom corner
            triangle(g, x+size/2, y, size/2);
            drawSierpinski(g, n-1, x+size/2, y, size/2);               
        }
    }
    
    public static void triangle(Graphics g, int x, int y, int size) {
        //calculate the height of the triangle
        //a triangle has three sides
        int height = (int)(size * Math.sqrt(3)/2), side = 3;
        //x and y coordinates calculation stuff
        int x1 = x - size/2, x2 = x + size/2;
        int y1 = y - height, y2 = y - height;
        int[] xCoordinates = {x, x1, x2};
        int[] yCoordinates = {y, y1, y2};
        //implement fillPoygon method to draw the triangle
        g.fillPolygon(xCoordinates, yCoordinates, side);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
